name: $(versionNumber).$(Rev:r)

variables:
    version: version
    versionNumber: 0.1.0

jobs:
    - job: Windows
      pool:
          vmImage: vs2017-win2016
      variables:
          artifactFileSuffix: .exe
      steps:
          - template: templates/build.yml

    - job: Linux
      pool:
          vmImage: ubuntu-16.04
      variables:
          artifactFileSuffix: -x86_64.AppImage
      steps:
          - template: templates/build.yml
