name: $(versionNumber)-rc.$(Rev:r)

trigger:
    - master

variables:
    version: version
    versionNumber: 0.1.0

jobs:
    - template: templates/build.yml
      parameters:
          name: Windows
          pool:
              vmImage: vs2017-win2016
          artifact: silver-bullet-cookbook Setup $(versionNumber).exe

    - template: templates/build.yml
      parameters:
          name: Linux
          pool:
              vmImage: ubuntu-16.04
          artifact: silver-bullet-cookbook-$(versionNumber).AppImage

    - template: templates/build.yml
      parameters:
          name: macOS
          pool:
              vmImage: macOS-10.13
          artifact: silver-bullet-cookbook-$(versionNumber).dmg
