name: $(version).$(Rev:rrrr)

pool:
    vmImage: vs2017-win2016

variables:
    version: 0.1

steps:
    - script: yarn install
      displayName: yarn install

    - script: yarn run build
      displayName: yarn run build

    - task: PublishTestResults@2
      displayName: Publish test results
      condition: succeededOrFailed()
      inputs:
          testResultsFiles: junit.xml
          testRunTitle: Jest Tests

    - task: PublishBuildArtifacts@1
      displayName: Publish artifact
      inputs:
          pathtoPublish: $(Build.SourcesDirectory)/dist/pepperzip Setup $(Build.BuildNumber).exe
          artifactName: $(projectName)
