name: $(versionNumber).$(Rev:r)

variables:
    version: version
    versionNumber: 0.1.0

jobs:
    - job: Build
      strategy:
          matrix:
              Windows:
                  vmImage: vs2017-win2016

              Linux:
                  vmImage: ubuntu-16.04

      pool:
          vmImage: $(vmImage)

      steps:
          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: Set version in package.json
            inputs:
                targetFiles: package.json

          - script: yarn install
            displayName: yarn install

          - script: yarn run build
            displayName: yarn run build

          - task: PublishTestResults@2
            displayName: Publish test results
            condition: succeededOrFailed()
            inputs:
                testResultsFiles: junit.xml
                testRunTitle: Jest Tests

          - task: PublishBuildArtifacts@1
            displayName: Publish artifact
            inputs:
                pathtoPublish: $(Build.SourcesDirectory)/dist/pepperzip Setup $(versionNumber).exe
                artifactName: Pepperzip
