pool:
    vmImage: vs2017-win2016

steps:
    - script: yarn install
      displayName: yarn install

    - script: yarn run build
      displayName: yarn run build

    - task: PublishTestResults@2
      displayName: Publish test results
      condition: succeededOrFailed()
      inputs:
          testResultsFiles: junit.xml
          testRunTitle: Jest Tests
