parameters:
    name: ""
    pool: ""
    artifact: ""

jobs:
    - job: ${{ parameters.name }}
      pool: ${{ parameters.pool }}
      steps:
          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: Set version in package.json
            inputs:
                targetFiles: package.json

          - task: NodeTool@0
            displayName: Use node 10.x
            inputs:
                versionSpec: 10.x

          - script: yarn install
            displayName: Install packages

          - script: yarn run build:tslint
            displayName: Run tslint

          - script: yarn run build:stylelint
            displayName: Run stylelint

          - script: yarn run build:test
            displayName: Run jest

          - script: yarn run build:webpack
            displayName: Run electron-webpack

          - script: yarn run build:electron
            displayName: Run electron-builder

          - task: PublishTestResults@2
            displayName: Publish test results
            condition: succeededOrFailed()
            inputs:
                testResultsFiles: junit.xml
                testRunTitle: ${{ parameters.name }} Jest Tests

          - task: PublishBuildArtifacts@1
            displayName: Publish artifact
            inputs:
                pathtoPublish: $(Build.SourcesDirectory)/dist/${{ parameters.artifact }}
                artifactName: Silver Bullet Cookbook
